# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsciiArtCli < Formula
  desc "Generates the URL link in various formats"
  homepage "https://github.com/hirabarufumitaka/ascii-art-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hirabarufumitaka/ascii-art-cli/releases/download/v0.2.1/ascii-art-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "5937590c98f33529f9608371df96e0a33a65d58b435ac98ba9bc2ebfade8da5c"

      def install
        bin.install "ascii-art-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hirabarufumitaka/ascii-art-cli/releases/download/v0.2.1/ascii-art-cli_0.2.1_darwin_x86_64.tar.gz"
      sha256 "88448ee691b6871ccdfb6157279cbb4f6e3a1e10e253ecae47cca818b7fb6f86"

      def install
        bin.install "ascii-art-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hirabarufumitaka/ascii-art-cli/releases/download/v0.2.1/ascii-art-cli_0.2.1_linux_x86_64.tar.gz"
      sha256 "2904434ac2c0ccaf5ba3489bfd0d8ba81e8f3ba5e9607ff12b5342c22b98905e"

      def install
        bin.install "ascii-art-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hirabarufumitaka/ascii-art-cli/releases/download/v0.2.1/ascii-art-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "34d245ca9a4e086c655a9203fda005bb74cc1573ad08a4cf3db32c7e3e11e929"

      def install
        bin.install "ascii-art-cli"
      end
    end
  end
end
